# Generated by Django 5.1.6 on 2025-04-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='default123', max_length=100),
            preserve_default=False,
        ),
    ]
