# Generated by Django 5.1.6 on 2025-04-13 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_doctordetails_profile_doctordetails_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetails',
            name='user',
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('admin', 'Admin'), ('user', 'User')], max_length=20),
        ),
    ]
