# Generated by Django 5.1.6 on 2025-04-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_remove_pet_image_pet_seller_alter_pet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
    ]
