# Generated by Django 5.1.6 on 2025-04-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0019_message_deleted_alter_message_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted',
        ),
    ]
