# Generated by Django 5.1.6 on 2025-04-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0022_pet_buyer_alter_pet_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default='No message'),
            preserve_default=False,
        ),
    ]
