# Generated by Django 5.1.6 on 2025-04-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0024_remove_feedback_date_submitted_remove_feedback_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
    ]
