# Generated by Django 5.1.6 on 2025-04-18 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0030_doctorclearancerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorclearancerequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_clearances', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorclearancerequest',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_clearances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorclearancerequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
