# Generated by Django 5.1.6 on 2025-04-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0033_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor'), ('admin', 'Admin')], max_length=10),
        ),
    ]
