# Generated by Django 5.1.6 on 2025-04-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0035_profile_phone_profile_specialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
