# Generated by Django 5.1.6 on 2025-04-20 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0036_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorclearancerequest',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='doctorclearancerequest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='doctorclearancerequest',
            name='user',
        ),
        migrations.AddField(
            model_name='doctorclearancerequest',
            name='requested_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requested_clearances', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorclearancerequest',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_clearances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorclearancerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
