# Generated by Django 5.1.6 on 2025-05-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0038_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
    ]
