# Generated by Django 5.1.6 on 2025-05-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0039_pet_is_adopted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('sold', 'Sold'), ('discount', 'Discount')], max_length=20)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
