# Generated by Django 5.1.6 on 2025-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0040_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_status',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('sold', 'Sold')], default='in_stock', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
